name: Deploy to iiumai DO Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/iiumai_key
          chmod 600 ~/.ssh/iiumai_key

      - name: Clean target
        run: |
          ssh -i ~/.ssh/iiumai_key -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} "rm -rf ${{ secrets.DO_TARGET }}/*"

      - name: Deploy build files
        run: |
          scp -i ~/.ssh/iiumai_key -o StrictHostKeyChecking=no -r dist/* ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }}:${{ secrets.DO_TARGET }}/
